feature-AP-6
ccem-dev/otus-app pull request #16
Opened 2020-06-17 19:50 UTC by fdrtec

Implementação do mecanismo para criação de chamados como projeto (Issues = ProjectContact ) e monitoramento de mensagens (+Testes unitários)

2020-06-18 21:27 UTC, drferreira commented on source/package.json
> +    "ngx-cookie": "^4.1.2",
@fdrtec remover ^ da dependencias para garantirmos a ultima versão porém fixa.

2020-06-18 21:32 UTC, drferreira requested changes
Verificar solicitações.

2020-06-19 11:22 UTC, fdrtec commented on source/package.json
> +    "ngx-cookie": "^4.1.2",
Solicitação corrigida

2020-06-19 13:11 UTC, drferreira approved these changes

2020-06-19 13:12 UTC, merged